### ISSUE TITLE
Github actions guide

### ISSUE THREAD

**Issue by sh1nj1** [vrerv/md-to-notion#5]
Common template

`./github/workflow/deploy-docs.yml`

```yaml
name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
  # manually run workflow
  workflow_dispatch:

jobs:
  deploy-docs-to-notion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          npx @vrerv/md-to-notion \
          -t ${{ secrets.NOTION_API_TOKEN }} \
          -p ${{ secrets.MD_TO_NOTION_PAGE_ID }} \
          -g ${{ github.repository }}/blob/${{ github.ref_name }} \
          -v .
```
